//Rr
export const GET_RR_DETAILS = 'GET_RR_DETAILS'
export const POST_RR_DETAILS = 'POST_RR_DETAILS'
export const UPDATE_RR_DETAILS = 'UPDATE_RR_DETAILS'
export const DELETE_RR_DETAILS = 'DELETE_RR_DETAILS'

//Rrbill
export const GET_RRBILL_DETAILS = 'GET_RRBILL_DETAILS'
export const POST_RRBILL_DETAILS = 'POST_RRBILL_DETAILS'
export const UPDATE_RRBILL_DETAILS = 'UPDATE_RRBILL_DETAILS'
export const DELETE_RRBILL_DETAILS = 'DELETE_RRBILL_DETAILS'

//Expense
export const GET_EXPENSE_DETAILS = 'GET_EXPENSE_DETAILS'
export const POST_EXPENSE_DETAILS = 'POST_EXPENSE_DETAILS'
export const UPDATE_EXPENSE_DETAILS = 'UPDATE_EXPENSE_DETAILS'
export const DELETE_EXPENSE_DETAILS = 'DELETE_EXPENSE_DETAILS'

//Expensebill
export const GET_EXPENSEBILL_DETAILS = 'GET_EXPENSEBILL_DETAILS'
export const POST_EXPENSEBILL_DETAILS = 'POST_EXPENSEBILL_DETAILS'
export const UPDATE_EXPENSEBILL_DETAILS = 'UPDATE_EXPENSEBILL_DETAILS'
export const DELETE_EXPENSEBILL_DETAILS = 'DELETE_EXPENSEBILL_DETAILS'

//OpdbILL
export const GET_OPDBILL_DETAILS = 'GET_OPDBILL_DETAILS'
export const POST_OPDBILL_DETAILS = 'POST_OPDBILL_DETAILS'
export const UPDATE_OPDBILL_DETAILS = 'UPDATE_OPDBILL_DETAILS'
export const DELETE_OPDBILL_DETAILS = 'DELETE_OPDBILL_DETAILS'